### ISSUE TITLE
[Bare] C : Todo creation function

### ISSUE THREAD

**Issue by yuhallo** [yuhallo/pre-project-react-tutorial#4]
### What do you want to create
Todo creation function

### What to do to implement that feature
1. [ ] Creating a list health management function
2. [ ] Send post request to fetch
3. [ ] Update the list and add a new TO DO

### Estimated working time
1d
