### ISSUE TITLE
[Bare] R : Todo view function

### ISSUE THREAD

**Issue by yuhallo** [yuhallo/pre-project-react-tutorial#5]
### What do you want to create
Todo view function

### What to do to implement that feature
1. [ ] Listing TO DO List
2. [ ] Add completion mark
3. [ ] To display a list of completed

### Estimated working time
1d
