### ISSUE TITLE
[Bare] U : Todo correction function

### ISSUE THREAD

**Issue by yuhallo** [yuhallo/pre-project-react-tutorial#6]
### What do you want to create
Todo correction function

### What to do to implement that feature
1. [ ] Create a Modify button
2. [ ] Send request to fetch
3. [ ] Update list to reflect modifications

### Estimated working time
1d
