### ISSUE TITLE
[Bare] D : Delete todo function

### ISSUE THREAD

**Issue by yuhallo** [yuhallo/pre-project-react-tutorial#7]
### What do you want to create
Delete todo function

### What to do to implement that feature
1. [ ] Create Delete button
2. [ ] Send delete request to fetch
3. [ ] To update deleted lists

### Estimated working time
1d
